version: 2.1

executors:
  default-execution-environment:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/build_directory
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

jobs:
  "Build Source":
    executor: default-execution-environment

    # Show some of the CircleCI runtime env variables
    steps:
      - run:
          command: |-
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
          name: "Show Runtime Environment Variables"
      - run:
          command: |-
            echo "uname:" $(uname -a)
            echo "arch: " $(arch)
          name: "Show System Information"

      # Checkout the source code
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Download Dependencies for Offline Use"
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Build project and persist results to workspace
      - run:
          name: "Build Source"
          command: mvn --batch-mode clean install
      - persist_to_workspace:
          root: ~/
          paths: build_directory

  "Release Source":
    executor: default-execution-environment
    steps:
      - attach_workspace:
          at: ~/

      # List working directory & contents
      - run: pwd && ls -ltr

workflows:
  version: 2

  "Check-In Build":
    jobs:
      - "Build Source"
      - "Approve Source Release":
          type: approval
          requires:
            - "Build Source"
          filters:
            branches:
              only:
                - development
      - "Release Source":
          requires:
            - "Approve Source Release"

  "Nightly Build":
    triggers:
      - schedule:
          cron: "59 23 * * *"
          filters:
            branches:
              only:
                - development
    jobs:
      - "Build Source"


