version: 2

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

jobs:
  build:
    executor: my-executor
    steps:
      # Checkout the source
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Build project
      - run: mvn --batch-mode clean install
  release:
    executor: my-executor
    steps:
      # Release project, placeholder command here right now
      - run: ls -ltr

workflows:
  version: 2
    build_and_release:
      jobs:
          - build
            - hold:
            filters:
              branches:
                only: development
            type: approval
            requires:
              - build
              - release:
                  requires:
                    - hold
      nightly_build:
        triggers:
          - schedule:
              cron: "0 0 * * *"
              filters:
                branches:
                  only:
                    - development
          jobs:
            - build


